### ISSUE TITLE
Phone

### ISSUE THREAD

**Issue by milkina** [tvoleg/OlegTveritnikov#1]
1. В классе рекомендуется сначала объявляются статические переменные, переменные класса, потом конструкторы, геттеры, сеттеры. Потом все остальные методы.
2. Переименуйте Phone в PhoneDemо. И PhoneMy в Phone.

**Comment by milkina** [comment]
Неотформатировано

**Comment by tvoleg** [comment]
исправил

**Comment by milkina** [comment]
не вижу разницы

**Comment by tvoleg** [comment]
отформатировал
