### ISSUE TITLE
Lesson 11. Book

### ISSUE THREAD

**Issue by milkina** [tvoleg/OlegTveritnikov#11]
printBook - вызовите этот метод.

**Comment by tvoleg** [comment]
исправил

**Comment by milkina** [comment]
1. Book - убрать комментарий
2.  Book - printBook  метод пустой зачем он?
3. Magazine - зачем здесь метод printBook?
4. Printable - Уберите printBook

**Comment by tvoleg** [comment]
вроде сделал
