### ISSUE TITLE
Shapes

### ISSUE THREAD

**Issue by milkina** [tvoleg/OlegTveritnikov#12]
1. http://www.examclouds.com/java/java-core-russian/checklist - проверьте все пункты
2. Уберите double x1, x2, x3, y1, y2; из Shape. Они там не имеют смысла
3. Классы Circle, Rectangle содержат координаты точек.

**Comment by tvoleg** [comment]
исправил

**Comment by milkina** [comment]
1. Shape - Переменные класса рекомендуется делать private.
2. Сircle - неотформатировно.
3. Класс Circle содержит координаты точек.

**Comment by tvoleg** [comment]
Класс Circle у меня содержит радиус, какие еще точки ему нужны?
