### ISSUE TITLE
Student, Aspirant

### ISSUE THREAD

**Issue by milkina** [tvoleg/OlegTveritnikov#13]
1.  http://www.examclouds.com/java/java-core-russian/checklist
2.  Уберите name из Aspirant

**Comment by tvoleg** [comment]
исправил

**Comment by milkina** [comment]
1. Aspirant - не отформатировано
2. Желательно переопределять в создаваемом классе методы toString, equals и hashCode.

**Comment by tvoleg** [comment]
добавил
