### ISSUE TITLE
lesson 17 HeavyBox2

### ISSUE THREAD

**Issue by milkina** [tvoleg/OlegTveritnikov#3]
В методе compareTo возвращается просто высота - 
int heavyBox2Height = heavyBox2.getHeight();
return this.height;
Надо возвращать разницу между высотами двух объектов.

**Comment by tvoleg** [comment]
Так а там в 
if (this.weight - heavyBox2Weight != 0) {
            return this.weight - heavyBox2Weight;
        } 
возвращается разница высоты, а в  else {
            int heavyBox2Height = heavyBox2.getHeight();
            return this.height;
        }
просто высота, разве не в этом суть?

**Comment by milkina** [comment]
Сделайте например так:
`@Override
    public int compareTo(HeavyBox2 heavyBox2) {
        int heavyBox2Weight = heavyBox2.getWeight();
        if (this.weight - heavyBox2Weight != 0) {
            return this.weight - heavyBox2Weight;
        } else {
            int heavyBox2Height = heavyBox2.getHeight();
            return this.height - heavyBox2Height;
        }
    }`

**Comment by tvoleg** [comment]
сделал
